import asyncio
from parser.core.models import ParseConfig
from parser.scheduler.scheduler import run_periodically
from parser.strategies import (
    ChernivtsiParser,
    BaseParser
)

parsers = [
    (
        ParseConfig(
            url="https://alerts.org.ua/rivnenska-oblast/",
            save_path="data/rivne.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/odeska-oblast/",
            save_path="data/odesa.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/volynska-oblast/",
            save_path="data/volyn.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/zaporizka-oblast/",
            save_path="data/zaporizhzhia.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/dnipropetrovska-oblast/",
            save_path="data/dnipro.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/ternopilska-oblast/",
            save_path="data/ternopil.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/vinnytcka-oblast/",
            save_path="data/vinnytsia.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/zhytomyrska-oblast/",
            save_path="data/zhytomyr.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/zakarpatska-oblast/",
            save_path="data/zakarpattia.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/ivano-frankivska-oblast/",
            save_path="data/ivano-frankivsk.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/kyivska-oblast/",
            save_path="data/kyivobl.json"
        ),
        BaseParser()
    ),
(
        ParseConfig(
            url="https://alerts.org.ua/kyiv/",
            save_path="data/kyivcity.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/kirovogradska-oblast/",
            save_path="data/kirovohrad.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/lvivska-oblast/",
            save_path="data/lviv.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/mykolaivska-oblast/",
            save_path="data/mykolaiv.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/poltavska-oblast/",
            save_path="data/poltava.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/sumska-oblast/",
            save_path="data/sumy.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/harkivska-oblast/",
            save_path="data/kharkiv.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/hmelnitcka-oblast/",
            save_path="data/khmelnytskyi.json"
        ),
        BaseParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/cherkaska-oblast/",
            save_path="data/cherkasy.json"
        ),
        BaseParser()
    ),    (
        ParseConfig(
            url="https://alerts.org.ua/chernivetcka-oblast/",
            save_path="data/chernivtsi.json"
        ),
        ChernivtsiParser()
    ),
    (
        ParseConfig(
            url="https://alerts.org.ua/chernigivska-oblast/",
            save_path="data/chernihiv.json"
        ),
        BaseParser()
    ),
]

asyncio.run(run_periodically(parsers))